/*
 * smoke_test.c — minimal smoke test for the GeometricMedicalPhantoms C API.
 *
 * Compile (Unix):
 *   cc -I ../include smoke_test.c -L ../build/lib -Wl,-rpath,\$ORIGIN/../build/lib \
 *      -lgeomphantoms -o smoke_test && ./smoke_test
 *
 * Compile (macOS):
 *   cc -I ../include smoke_test.c -L ../build/lib \
 *      -Wl,-rpath,@loader_path/../build/lib -lgeomphantoms -o smoke_test && ./smoke_test
 *
 * Compile (Windows / MSVC, with import lib generated by JuliaC):
 *   cl smoke_test.c /I ..\include /link /LIBPATH:..\build\lib geomphantoms.lib
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "geometric_medical_phantoms.h"

#define CHECK(ret, msg)                                          \
    do {                                                         \
        if ((ret) != 0) {                                        \
            fprintf(stderr, "FAIL [%s]: error code %d\n", msg, ret); \
            return 1;                                            \
        }                                                        \
    } while (0)

int main(void)
{
    int ret;

    /* --- version --------------------------------------------------------- */
    const char *ver = gmp_version();
    printf("[version] %s\n", ver);

    /* --- Shepp-Logan 3-D ------------------------------------------------- */
    {
        const int nx = 16, ny = 16, nz = 16;
        float *buf = (float *)malloc((size_t)nx * ny * nz * sizeof(float));
        if (!buf) { fputs("malloc failed\n", stderr); return 1; }

        GmpSheppLoganIntensities sl;
        gmp_shepp_logan_ct_default(&sl);

        ret = gmp_create_shepp_logan_phantom_3d(nx, ny, nz, &sl, buf);
        CHECK(ret, "create_shepp_logan_phantom_3d");

        int nonzero = 0;
        for (int i = 0; i < nx * ny * nz; i++)
            nonzero += (buf[i] != 0.0f);
        printf("[shepp_logan_3d] %d / %d non-zero voxels\n", nonzero, nx * ny * nz);
        if (nonzero == 0) { fputs("All voxels are zero!\n", stderr); free(buf); return 1; }

        free(buf);
    }

    /* --- Shepp-Logan 2-D (axial slice) ----------------------------------- */
    {
        const int nx = 32, ny = 32;
        float *buf = (float *)malloc((size_t)nx * ny * sizeof(float));
        if (!buf) { fputs("malloc failed\n", stderr); return 1; }

        GmpSheppLoganIntensities sl;
        gmp_shepp_logan_mri_default(&sl);

        ret = gmp_create_shepp_logan_phantom_2d(nx, ny, GMP_AXIS_AXIAL, 0.0, &sl, buf);
        CHECK(ret, "create_shepp_logan_phantom_2d");
        printf("[shepp_logan_2d] first value: %f\n", (double)buf[0]);

        free(buf);
    }

    /* --- Tubes 3-D ------------------------------------------------------- */
    {
        const int nx = 16, ny = 16, nz = 16;
        float *buf = (float *)malloc((size_t)nx * ny * nz * sizeof(float));
        if (!buf) { fputs("malloc failed\n", stderr); return 1; }

        GmpTubesGeometry tg;
        gmp_tubes_geometry_default(&tg);

        const int n_tubes = 6;
        double fillings[6];
        GmpTubesIntensities ti;
        gmp_tubes_intensities_default(&ti, fillings, n_tubes);

        ret = gmp_create_tubes_phantom_3d(nx, ny, nz, &tg, &ti, buf);
        CHECK(ret, "create_tubes_phantom_3d");

        int nonzero = 0;
        for (int i = 0; i < nx * ny * nz; i++)
            nonzero += (buf[i] != 0.0f);
        printf("[tubes_3d] %d / %d non-zero voxels\n", nonzero, nx * ny * nz);
        if (nonzero == 0) { fputs("All voxels are zero!\n", stderr); free(buf); return 1; }

        free(buf);
    }

    /* --- Respiratory signal ---------------------------------------------- */
    {
        const double duration = 10.0, fs = 50.0, rr = 15.0;
        int n = gmp_signal_length(duration, fs);
        printf("[signal_length] %.0f s @ %.0f Hz -> %d samples\n", duration, fs, n);
        if (n <= 0) { fputs("Signal length is zero!\n", stderr); return 1; }

        double *t   = (double *)malloc((size_t)n * sizeof(double));
        double *sig = (double *)malloc((size_t)n * sizeof(double));
        if (!t || !sig) { fputs("malloc failed\n", stderr); return 1; }

        GmpRespiratoryPhysiology phys;
        gmp_respiratory_physiology_default(&phys);

        ret = gmp_generate_respiratory_signal(duration, fs, rr, &phys, t, sig, n);
        CHECK(ret, "generate_respiratory_signal");

        double sig_min = sig[0], sig_max = sig[0];
        for (int i = 1; i < n; i++) {
            if (sig[i] < sig_min) sig_min = sig[i];
            if (sig[i] > sig_max) sig_max = sig[i];
        }
        printf("[respiratory] range [%.3f, %.3f] L  (t[0]=%.3f, t[%d]=%.3f)\n",
               sig_min, sig_max, t[0], n - 1, t[n - 1]);

        if (sig_min < 1.0 || sig_max > 5.0) {
            fputs("Respiratory signal out of expected range!\n", stderr);
            free(t); free(sig); return 1;
        }

        free(t);
        free(sig);
    }

    /* --- Cardiac signals ------------------------------------------------- */
    {
        const double duration = 5.0, fs = 200.0, hr = 70.0;
        int n = gmp_signal_length(duration, fs);

        double *t  = (double *)malloc((size_t)n * sizeof(double));
        double *lv = (double *)malloc((size_t)n * sizeof(double));
        double *rv = (double *)malloc((size_t)n * sizeof(double));
        double *la = (double *)malloc((size_t)n * sizeof(double));
        double *ra = (double *)malloc((size_t)n * sizeof(double));
        if (!t || !lv || !rv || !la || !ra) { fputs("malloc failed\n", stderr); return 1; }

        GmpCardiacPhysiology phys;
        gmp_cardiac_physiology_default(&phys);

        ret = gmp_generate_cardiac_signals(duration, fs, hr, &phys, t, lv, rv, la, ra, n);
        CHECK(ret, "generate_cardiac_signals");

        printf("[cardiac] lv[0]=%.1f mL, rv[0]=%.1f mL, la[0]=%.1f mL, ra[0]=%.1f mL\n",
               lv[0], rv[0], la[0], ra[0]);

        if (lv[0] < 10.0 || lv[0] > 300.0) {
            fputs("LV volume out of expected range!\n", stderr);
            free(t); free(lv); free(rv); free(la); free(ra); return 1;
        }

        free(t); free(lv); free(rv); free(la); free(ra);
    }

    /* --- Static torso 3-D ------------------------------------------------ */
    {
        const int nx = 16, ny = 16, nz = 16;
        float *buf = (float *)malloc((size_t)nx * ny * nz * sizeof(float));
        if (!buf) { fputs("malloc failed\n", stderr); return 1; }

        GmpTissueIntensities ti;
        gmp_tissue_intensities_default(&ti);

        ret = gmp_create_torso_phantom_3d(nx, ny, nz, 0,
                                          NULL, NULL, NULL, NULL, NULL,
                                          &ti, buf);
        CHECK(ret, "create_torso_phantom_3d (static)");

        int nonzero = 0;
        for (int i = 0; i < nx * ny * nz; i++)
            nonzero += (buf[i] != 0.0f);
        printf("[torso_3d] %d / %d non-zero voxels\n", nonzero, nx * ny * nz);
        if (nonzero == 0) { fputs("All voxels are zero!\n", stderr); free(buf); return 1; }

        free(buf);
    }

    puts("\n=== All smoke tests passed ===");
    return 0;
}
